script: make travis
language: go
go:
  - 1.4
  - 1.5
  - tip
install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/dchest/uniuri
  - go get github.com/nfnt/resize
  - go get github.com/rlmcpherson/s3gof3r
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin
